# -*- coding: utf-8 -*-
"""The Rai bazaar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nerZzkguE0cl8lZVu51qWpSb6OqWHTU
"""

a=int(input("The value of a "))
b=int(input("The value of b "))
c=int(input("The value of c "))
d=a+b+c
if(d>50):
  print(f" After  Discount {d-(d/100)*10} ")
else:
        print(f" Before Discount {d} ")